---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: RedHat-Apache2.2.yml
  when: ansible_os_family == "RedHat" and ansible_distribution_version|int == 6

- include: Debian-Apache2.4.yml
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "12.04"

- include: Debian-Apache2.4.yml
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "13.10"

- include: Debian-Apache2.4.yml
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04"

- name: Create DocumentRoots
  file: >
    state=directory
    path={{ item.documentroot }}
    owner={{ item.owner|default(apache_default_owner) }}
    group={{ item.group|default(apache_default_group) }}
    mode={{ item.mode|default('0755') }}
  with_items:
    apache_vhosts
  when:
    apache_vhost_create_docroots and apache_vhosts.0 is defined

- name: Enable and start service
  service: >
    name="{{ apache_daemon }}"
    state="started"
    enabled="yes"

